Added contact-me section
ritikarawat220/My-Portfolio pull request #6
Opened 2023-01-17 08:21 UTC by ritikarawat220

This branch contains:

   - Toolbar
   - Headline
   - Works
   - About Me
   - Contact Me

2023-01-17 13:12 UTC, KanzaTahreem requested changes
# Changes Required 🔁

**Hi team 👋**

Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! 

**_However, I did notice a few areas where some additional changes would further enhance the quality of the code. But you are almost there!_** 💪


![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

- ✅ Well done so far following the given Figma design
- ✅ Excellent job with CSS
- ✅ Descriptive PR and README file
- ✅ Correct Linters

However, there is always room for improvement. 

## Required Changes ♻

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 13:12 UTC, KanzaTahreem commented on index.html
> +          <form class="contact-form" action="#" method="post">
- [x] Please make sure that you collect data by using the [Formspree service](https://formspree.io/html) according to the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). Following is a quote for a related requirement 🔽

  > _Collect data by using the [Formspree service](https://formspree.io/html)._


- [x] You can do this by following the guidelines from [here](https://formspree.io/html/) 🔗. Kindly ensure that your `action` attribute is similar to the one mentioned below 🔽. However, make sure that you use your personalized `form id`.
![image](https://user-images.githubusercontent.com/106119105/212893407-26216f0b-835a-4a62-bdfd-870c1bcc1923.png)

- [x] Also please ensure that you are able to collect data using the Formspree service. Right now, when I'm trying to do that, I'm receiving the following error 🔽 You can see how it's done from [here](https://www.youtube.com/watch?v=taa8Kiong0o). You can skim through the tutorial and focus on your requirements.
![image](https://user-images.githubusercontent.com/106119105/212894293-ee33dc2e-8b93-4e72-989a-db3573d18fbd.png)

2023-01-17 13:12 UTC, KanzaTahreem commented on index.html
> +            type="email" id="mail" name="user_email" required/>
- [x] I can see that you have added a placeholder text for `<textarea>`, great job doing that, 👍 but it is missing for other `<input>` fields. Let's make sure that all the input fields have the correct associated **placeholder** text as mentioned in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). Below is the quote for related requirement 🔽

  > _All fields have placeholder text._


- [ ] If you see the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=iwXxMCz8rsmQKNXV-0), there are no labels for input fields, that's why it will be difficult for user to understand what kind of input is expected.  Also, placeholder text can improve the usability and user experience of a website 🤩 

- [ ] Also, please add a little more space between input fields so that your design is exact replica of the figma design. I know you can do that 💪

## **_Your design 👇_**
![image](https://user-images.githubusercontent.com/106119105/212905876-2f3cc094-8600-455a-b792-2e088456c086.png)

## **_Figma design 👇_**
![image](https://user-images.githubusercontent.com/106119105/212905825-22da79df-9a56-4bf3-b8eb-04e5ace25ccb.png)

2023-01-17 13:12 UTC, KanzaTahreem commented on index.html
> +            <input type="text" id="name" name="user_name" required />
- [x] Please make sure that your `name field` accepts up to _**30 chars**_ as mentioned in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). Below is a quote for a related requirement 🔽

  > _Name field accepts up to 30 chars._

2023-01-17 13:12 UTC, KanzaTahreem commented on index.html
> +             placeholder="Write your message here" required></textarea>
- [x] Let's make sure that `message field` accepts up to **_500 chars_** as mentioned in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). Below is a quote for a related requirement 🔽

  > _Message field accepts up to 500 chars._

You can do that by adding a `maxlength` attribute to your fields. To learn more about the attribute, please click [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength). I know you can do that 💪

- [x] Also, please make sure that you follow the figma design as much as possible according to the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). You are almost there, please fix the `font-family` for `<textarea>` to match the figma design

## **_Your design 👇_**
![image](https://user-images.githubusercontent.com/106119105/212901114-d1e032be-b39b-4161-8f66-ee60549859a3.png)

## **_Figma design 👇_**
![image](https://user-images.githubusercontent.com/106119105/212901184-d940bbd0-5cb7-4b40-99d7-88ecbb17dbba.png)

2023-01-17 13:12 UTC, KanzaTahreem commented on index.html
> +        <section class="contact-me">
- [x] Please ensure that you use `flexbox` to layout the elements as mentioned in the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). Below is a quote for a related requirement 🔽. Right now your are using `grid` to style your contact section. Please fix this according to the requirement. I know you can do that 💪

  > _In order to lay out the elements on the page you should use Flexbox._

2023-01-17 13:12 UTC, KanzaTahreem commented on index.html
> +             <button class="btn-submit" type="submit">Get It Touch</button>
- [x] Excellent job adding a hover effect to your submit button 👍. Let's make sure that you yo don't forget to follow the other button interactions according to the figma design.
- [x] Right now, your button lacks `pressed` and `disabled` interactions. For example, you can use `button:active` and `button:disabled` to style your button accordingly. For more clarity, please click [here for active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active#:~:text=The%20%3Aactive%20CSS%20pseudo%2Dclass,down%20the%20primary%20mouse%20button.), and [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled) to know more about disabled CSS [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)

## Figma button interactions 👇
![image](https://user-images.githubusercontent.com/106119105/212904744-5032dbd9-6d54-4b63-b05a-aabff65f2750.png)

2023-01-17 13:12 UTC, KanzaTahreem commented on style.css
> +
- [ ] You are almost there. Just one step to go 🏁 Please ensure that you follow the figma design as much as possible. Right now, your background has a different color. Kindly make sure that you fix this. I know you can do that 💪 For example, you can do that by simple adding a background color `background-color: #fff` to your `footer`, something like below 🔽

## **_Your design 👇_**
![image](https://user-images.githubusercontent.com/106119105/212906498-4af15ed1-95bf-41cf-8448-57328181991e.png)

## **_FIgma design 👇_**
![image](https://user-images.githubusercontent.com/106119105/212906560-a0893027-fd2f-4638-843d-310eaf11ac1f.png)

2023-01-17 15:32 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @ritikarawat220 , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

https://github.com/ritikarawat220/My-Portfolio/blob/1d3c50ab54fac58ffcc8e73cd60bf1820974c623/style.css#L17-L20
- [ ] You did a great job by implementing all requirements suggested by the previous however you still need to fix the smallest one which remains about the background color  Please fix that as required by the previous reviewer [ here](https://github.com/ritikarawat220/My-Portfolio/pull/6#discussion_r1072185758)it will make your design stick to the Figma design at 100%  To do that I just suggest you apply that grey  background color to the card section and white color do other sections 

Here your design still has the grey background please fix that

![image](https://user-images.githubusercontent.com/95297251/212940542-651b8ec2-d85a-4264-b1d1-8f0bf7ad23e8.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] [OPTIONAL] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-18 06:54 UTC, OyePriscilla approved these changes
Hi team  😄, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
✔️Made the required changes👍
✔️No linter errors👍
✔️GitHub flow observed👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 06:56 UTC, merged